a := one two# a is assigned to the string "one two"
b := 'one two' # Not recommended. b is assigned to the string "'one two'"
all:
	printf '$a'
	printf $b

x := dude
var2:
	echo $(x)
	echo ${x}

	# Bad practice, but works
	echo $x 